### ISSUE TITLE
Can't change expected config file paths for custom scans

### ISSUE THREAD

**Issue by esen-transporeon** [rancher/cis-operator#159]
Hello,

I followed the rancher [documentation ](https://rancher.com/docs/rancher/v2.6/en/cis-scans/custom-benchmark/) to create my custom benchmark since my config files where deployed at a custom path. After configuring the right paths the checks for the config files still failed. 

I think it is related to the host and mount paths of the rke2-root in the [security scan plugin config template](
https://github.com/rancher/cis-operator/blob/43566973ce67787b37236ae3e499930942a144ec/pkg/securityscan/core/templates/pluginConfig.template) which are hard-coded to /var/lib/rancher. 

Because when I changed the expected config paths in the scan to custom paths under /var/lib/rancher, for example /var/lib/rancher/test/scheduler.conf, it works but for other custom paths, like /srv/scheduler.conf, it fails.

I of course always placed the files to the right place with the right permission to test the behavior of the scan.

A solution could be to provide a variable to overwrite the paths of the rke2-root in the [security scan plugin config template](
https://github.com/rancher/cis-operator/blob/43566973ce67787b37236ae3e499930942a144ec/pkg/securityscan/core/templates/pluginConfig.template).

Thanks in advance!

**Comment by MKlimuszka** [comment]
@mitulshah-suse , you can decide if this is an enhancement worth pursuing.

**Comment by vardhaman22** [comment]
@esen-transporeon the rke2-root path is used by other benchmarks so if we provide a variable for this and somebody change it then other benchmarks will not work in expected way.
The thing which you wanted to do is to refer files from the config files which are not in /var/lib/rancher, you can do that by just adding /node prefix to the path of those files and refer them in the config.yaml of custom benchmark. Since the root volume of the node is mounted on /node path of the pod.
so as per your example if you have placed the file on the node at path /srv/scheduler.conf then you can use /node/srv/scheduler.conf in the config.yaml of you custom benchmark. Ref: [L102](https://github.com/rancher/cis-operator/blob/43566973ce67787b37236ae3e499930942a144ec/pkg/securityscan/core/templates/pluginConfig.template#L102) and [32](https://github.com/rancher/cis-operator/blob/43566973ce67787b37236ae3e499930942a144ec/pkg/securityscan/core/templates/pluginConfig.template#L32) of [security-scan plugin template](https://github.com/rancher/cis-operator/blob/43566973ce67787b37236ae3e499930942a144ec/pkg/securityscan/core/templates/pluginConfig.template)

**Comment by esen-transporeon** [comment]
Thanks for the explanation. We decided to just use the default path to solve this problem but I can comprehend your solution. That would have probably worked that way. This Issue can be closed.
