### ISSUE TITLE
CIS Scans failing with gke-1.2.0 or gke-1.0 benchmarkVersion

### ISSUE THREAD

**Issue by konih** [rancher/cis-operator#216]
Our CIS Scans on GKE Clusters with Kubernetes Version v1.26.1 are crashing in the daemonset pods. Jobs are left in pending state. It is required to restart the cis operator pod, before another scan will be attempted. We tried with helm chart versions 3.0.0, 4.0.0 and 4.1.0 and CIS Operator image version v1.0.9 and v1.0.12.  The `rancher-kube-bench` pod causes the error, but the debug output was not helpful in discerning the cause. The pods are deleted so fast, that we can't drill deeper. Executing the scans with similar paremeters using `aqua/kubebench` native was successful.

```
Defaulted container "rancher-kube-bench" out of: rancher-kube-bench, sonobuoy-worker
+ DEBUG_TIME_IN_SEC=300
+ test 0 '!=' 0
+ trap handle_error ERR
+ IS_RKE2=false
+ pgrep rke2
+ IS_K3S=false
+ pgrep k3s
+ set +x
Rancher Kubernetes Version: v1.25.10-gke.2700
+ RANCHER_K8S_VERSION=v1.25.10-gke.2700
+ echo 'Rancher Kubernetes Version: v1.25.10-gke.2700'
+ TAR_FILE_NAME=kb
+ CONFIG_DIR=/etc/kube-bench/cfg
+ [[ /etc/kube-bench/cfg != \/\e\t\c\/\k\u\b\e\-\b\e\n\c\h\/\c\f\g ]]
+ RESULTS_DIR=/tmp/sonobuoy
+ ERROR_LOG_FILE=/tmp/sonobuoy/error.log
+ LOG_DIR=/tmp/sonobuoy/logs
+ JOURNAL_LOG=/var/log/journal
++ journalctl -D /var/log/journal --lines=0
++ grep -s 'No such file or directory'
++ wc -l
+ [[ 0 -gt 0 ]]
+ mkdir -p /tmp/sonobuoy
+ [[ gke-1.2.0 != '' ]]
++ grep etcd
++ ps -e
++ wc -l
+ [[ 0 -gt 0 ]]
++ journalctl -D /var/log/journal -u k3s -u k3s-agent
++ grep -wv 'No entries'
++ grep -wv 'Logs begin'
++ wc -l
+ [[ 0 -gt 0 ]]
+ [[ gke-1.2.0 != '' ]]
++ pgrep kube-apiserver
++ wc -l
+ [[ 0 -gt 0 ]]
++ journalctl -D /var/log/journal -u k3s
++ grep 'Running kube-apiserver'
++ grep -v grep
++ wc -l
+ [[ 0 -gt 0 ]]
+ kubeletconf=/node/var/lib/kubelet/config
+ [[ gke-1.2.0 != '' ]]
++ pgrep kubelet
++ wc -l
+ [[ 1 -gt 0 ]]
+ echo 'node: Using OVERRIDE_BENCHMARK_VERSION=gke-1.2.0'
+ kube-bench run --targets node --scored --nosummary --noremediations --v=0 --config-dir=/etc/kube-bench/cfg --benchmark gke-1.2.0 --json --log_dir /tmp/sonobuoy/logs --outputfile /tmp/sonobuoy/node.json
node: Using OVERRIDE_BENCHMARK_VERSION=gke-1.2.0
++ handle_error
++ [[ '' == \t\r\u\e ]]
++ echo -n /tmp/sonobuoy/error.log
```

**Comment by andypitcher** [comment]
@konih thanks for reporting the issue, and apologies for the late reply. 
The helm chart version you referred to, are bound to the following rancher/security-scan versions:

- 3.0.0 -> v0.2.9
- 4.0.0 -> v0.2.11
- 4.1.0 -> v0.2.12

There is known issue in security-scan:v0.2.12, where upstream's profiles are absent such as GKE/AKS/EKS, so that could partly explain the behaviour. That said this issue isn't present in the previous and latest version of `rancher/security-scan`.

Could you specify what version of Rancher you're using ? I would also recommend to resintall/update the `CIS Benchmark` by providing rancher/security-scan:v0.2.13 in the helm chart, as shown below:


![](https://user-images.githubusercontent.com/12878731/272332257-dbcbed66-d2a1-4239-8d34-3589dbafb7cf.png)


![](https://user-images.githubusercontent.com/12878731/272332418-cea19541-a221-432c-8fa2-3433ba7a0f87.png)


Thanks.

**Comment by andypitcher** [comment]
@konih should we keep this issue open ? Let us know if you still need some help there. Thanks

**Comment by andypitcher** [comment]
@konih I'll close this issue, feel free to reopen it if needed.
