### ISSUE TITLE
Scan with failed status does not fire a AlertOnFailure alert

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#68]
**On 2.5-head - latest**

- Configure Monitoring and alerting on a cluster
- Deploy CIS v2 app
- Create a scan CR.
- Enable `AlertOnFailure` alerts
- Create a CIS permissive scan run and give in `Scan state for "warn" results: Fail`
- The scan runs and the state of the scan is "Fail"
- But no alerts are triggered.

Can we trigger alerts for "Failed" scans also ? Those that have no "Failed" tests but have a "failed" scan state?

**Comment by prachidamle** [comment]
The AlertOnFailure is not tied with the "failed" status but with "non-zero" test failures. Since there were no tests that failed, there will not be an alert which is triggered only when number of tests failed is non-zero. 

Currently the alerts are tied with prometheus metrics that are exported by cis-operator. The operator increments the "cis_scan_num_tests_fail" metric when there are test failures which drives alertmanager to fire alert.

If we want to also drive alerts if there are tests with "warn" status, we need to add another metric and an option AlertOnWarn
cc @deniseschannon does this sound like a new addition we need?

**Comment by prachidamle** [comment]
@deniseschannon confirmed that we should send out an alert for AlertOnFailure as user has indicated that warn = fail

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `baf4867` with latest cis v2 charts: `rancher-cis-benchmark:1.0.300`**

- Create a CIS v2 scan CR with Alert on for "failures" and select rke-permissive cis 1.5 scan profile with "warn" as fail
- Alerts are fired.
